name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          theme: night-rainbow   # ou outro tema que preferir
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📊 Atualiza gráfico 3D"
          branch: main
          file_pattern: profile-3d-contrib/*.svg
